sudo: required
services:
  - docker

before_install:
  - docker build -t docker1z3d/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker1z3d/react-test npm run test

after_success:
  - docker build -t docker1z3d/multi-client ./client
  - docker build -t docker1z3d/multi-nginx ./nginx
  - docker build -t docker1z3d/multi-server ./server
  - docker build -t docker1z3d/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push docker1z3d/multi-client
  - docker push docker1z3d/multi-nginx
  - docker push docker1z3d/multi-server
  - docker push docker1z3d/multi-worker
